name: ksiegi_emilki
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"

  web:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
